services:
  backend:
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  backend-test:
    build:
      context: ./spring
      dockerfile: Dockerfile.test
    env_file:
      - .env