services:
  backend:
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./spring:/app
    command: ["java", "-jar", "app.jar"]

  backend-test:
    build:
      context: ./spring
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./spring:/app
    command: ["./gradlew", "test"]
