spring:
  datasource:
    url: jdbc:postgresql://roadit-db.ch0u80kuupqm.ap-northeast-2.rds.amazonaws.com:5432/roadit_db
    username: roadit_superuser
    password: road!tdb
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true

  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: AKIA3CB2U5XWWH6P3RFD
    password: BGHeKhd17BjqhI6+wcITEVoltDgTycrl8yGo9p1NmCHO
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

server:
  port: 8080


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace